language: node_js
node_js:
- node
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: apikey
  organization: sonaysevik@gmail.com
  space: dev
  manifest: manifest.yml
  password:
    secure: YKnxjo1faM00o1jP71+bmuMDZZulCyP5Zjiv2jKSoIFcH9WSga9OOxox0eqfdJY9Ge5Ahb3uEsbKCGycnmxFugn32Dak+ebEVw1YpyWycGZ+PunrmAYfuidXK5lyw0jXvZwjTxlXCnYmRUfnqow3GodVwJ3PRnfcm/HJU4sr2by4dEZldKWXepSPnG+Vw1eTWa+HFl95TB2/0P8pirV6CbaCKi76RLmLvo+vc2ZqolqESCmhkjV8ehY8JiwFJDq2/nbf5OQe6W6OvV9ww3E81Cthu8qg4Ex+n4cMozv9lf1+3IcR9D0qpgpdkSWFHEH6Tr80Rt7ZJGAxXSCX4myG1sWkJYzAd5DTu5sCwjfuueCB63Vcl/otRRmpG0/PvM22214WDgeqwBX8V0OTG7RC3Te/rEbk441pWaA3sY6ppOZ3VbfnyOjJXKpvhDtt8UxePdWYavDu6afusImSyLyCNvuuM/KTRR3a56I4cnrOHOKIM26p55HC/fcuopgdAm2sDyRXk3jHyNnPPKgUVE+o/fpFR7WY55Bwh/I2g1GystdTuXBr+XZrdsfwbQZ9X6a+cJeMdJQwURlUQ7EqLK/zLzv9w8GNFKwq907pjl2rTKMncTi6EOGn3WtBj6OlDoY04HT/SoJuTr/iHHQ2/d9g1IX1c9m85Ui09mcPZTt0btM=
