language: node_js
node_js:
- node
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: apikey
  organization: sonaysevik@gmail.com
  space: dev
  manifest: manifest.yml
  password:
    secure: o6cf4aGZZ55oetA7uajLzwno9xHuqndvca6cK7mig+0+SSJMBPpOsaGSrBjF3ZG8WPlBQJgwaGkoc3y2Wj6T1cPkKKYNIWgTr8pnOPyjm+1aSdf7uAPuQkwcKHuAZwnkG6O0iTtX8PQZa76rxDakIEbZMG6jv3YyyJ+WkVDLPp6fIjczKT73w9Fg3s8eql1+EyKDZ5HkZO4I0+77x0tx0465lyuuxgK7d4qOIjF5953DxEmaYe+vKUUzay8D1V1kEKieCdBo4lmxwu/T/W8m2upAZXbZo0EtOBGSuGRWQfQp5BBSEPThJgUzNPv9lZiL3FaduPUaUaXHFML4mf3NYN9Zyxf9C+hkBszrcaZmMjTr1JVQdCkdObgDO8gKQGzMU59nWttEwclqzsV5XwbQ5O1tdfxCh5IFty7DTfl471nmoj6AAh4qZaREPnBrpXFssL9A1bH62ZhgHer0t7ZWJZac6cR07cLJxoNv7uTmmqZbhF3Kg/saiznK/UaKFWuqLQUoTnKioEIeKWFhfBXbMftOdZ5yEHW5wSWdsRonnPQA4Oa+EC3iNYCf/RdZUrNKkFHKT1UWnJlAubiLtbboMel904ND3kPPk3Dq3f32pcKmHPbPrxCnmn56fdItUGsL3OhHOgmNDqJkGNglJ4h34B9RRaTQ+alHtdO3OQoLGNY=
